services:
  server:
    build:
      context: .
    container_name: url-shortener-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    container_name: mongo-database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
  redis_data:


networks:
  app-network:
    driver: bridge
